#!/usr/bin/env bash
if [[ "$BLOCK_BUTTON" -eq 1 ]]; then
   lscpu|grep MHz|awk -F ':' '{print $2}'|paste -sd " " -| awk '{printf("%.2f \\ ",$1);printf("%.2f \\ ",$1/$2);printf("%.2f ",$1/$3)}'
else
    lscpu|grep MHz|awk -F ':' '{print $2}'|paste -sd " " -| awk '{printf("%.2f ",$1);}'
fi
